blog/urls.py
from . import views
from django.urls import path

app_name = 'blog_app'
urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:post_id>', views.post_detail, name="post_detail"),
    path('<slug:category_slug>', views.post_list, name='post_list_by_category'),
    path('share/<int:post_id>', views.post_share, name='post_share'),
    # path('search/',views.search_post,name='search_post')
]

my_blog_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace="blog_app"))

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone


class Category(models.Model):
    name = models.CharField(max_length=80)
    slug = models.SlugField(max_length=80)

    class Meta:
        ordering = ('name',)
        db_table = 'category'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog_app:post_list_by_category', args=[self.slug])


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')


class Post(models.Model):
    published = PublishedManager()
    CHOICES = (('draft', 'Draft'), ('published', 'Published'))
    title = models.CharField(max_length=250)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    slug = models.SlugField(unique_for_date='publish')
    author = models.ForeignKey(User, related_name='posts', on_delete=models.CASCADE)
    publish = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=50, choices=CHOICES, default='draft')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='posts', blank=True, null=True)
    image = models.ImageField(upload_to='images/%y/%m/%d/', blank=True, null=True,
                              default='images/blank-img.jpg')

    class Meta:
        ordering = ('-created',)
        db_table = 'post'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog_app:post_detail', args=[self.id])


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    active = models.BooleanField(default=False)
    name = models.CharField(max_length=80)
    message = models.TextField()
    email = models.EmailField()
    time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('time',)
        db_table = 'comment'

blog/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'message')


class SendEmailForm(forms.Form):
    name = forms.CharField(max_length=50)
    email = forms.EmailField()
    contact_email = forms.EmailField()
    message = forms.CharField(required=False,
                              widget=forms.Textarea(attrs={'class': 'md-textarea form-control', 'rows': '3'}))


class SearchForm(forms.Form):
    query = forms.CharField(max_length=200, required=True, widget=forms.TextInput(
        attrs={'class': "form-control mr-sm-2", 'type': "text", 'placeholder': "Search", 'aria-label': "Search"}))

blog/views.py
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.core.mail import send_mail
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Count
from django.shortcuts import render, get_object_or_404

from blog.forms import CommentForm, SendEmailForm, SearchForm
from blog.models import Post, Comment, Category


def post_list(request, category_slug=None):
    query = None
    results = []
    form = SearchForm()
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_query = SearchQuery(query)
            search_vector = SearchVector('title', weight='A') + SearchVector('body', weight='B')
            search_rank = SearchRank(search_vector, search_query)
            results = Post.published.annotate(rank=search_rank).filter(rank__gte=0.1).order_by('-rank')
    if category_slug:
        posts = Post.published.filter(category__slug=category_slug)
    else:
        posts = Post.published.all()
    recent_posts = Post.published.all()[:3]
    popular_post = Post.published.annotate(num_comments=Count('comments')).order_by('-num_comments')[:3]
    categories = Category.objects.all()
    paginator = Paginator(posts, 5)
    current_page_number = request.GET.get('page')
    try:
        posts = paginator.page(current_page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/home.html',
                  {'posts': posts, 'recent_posts': recent_posts, 'popular_posts': popular_post,
                   'categories': categories, 'results': results, 'form': form, 'query': query})


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    recommended_posts = Post.published.filter(category=post.category).exclude(pk=post_id)
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.active = False
            new_comment.post = post
            new_comment.save()
    else:
        form = CommentForm()
    return render(request, 'blog/post.html',
                  {'post': post, 'form': form, 'new_comment': new_comment, 'comments': comments,
                   'recommended_posts': recommended_posts})


def post_share(request, post_id):
    send = False
    post = get_object_or_404(Post, id=post_id)
    if request.method == 'GET':
        form = SendEmailForm()
    else:
        form = SendEmailForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            subject = "post_share"
            message = "{} with this email: {} send this post ".format(cd['name'], cd[
                'email']) + '\n' + request.build_absolute_uri(post.get_absolute_url())
            send_mail(subject, message, cd['email'], [cd['contact_email'], ])
            send = True

    return render(request, 'blog/share.html', {'form': form, 'send': send})

blog/templates/blog/post.html
{% load static %}
{% load blog_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Material Design Bootstrap Template</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{% static "css/mdb.min.css" %}" rel="stylesheet">

</head>

<body class="postpage-v2">

<!-- Navigation -->
<header>

    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark stylish-color-dark">

        <!-- Navbar brand -->
        <a class="navbar-brand" href="#">My Personal Blog</a>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">

            <span class="navbar-toggler-icon"></span>

        </button>

    </nav>
    <!-- Navbar -->

</header>
<!-- Navigation -->

<!-- Main layout -->
<main>

    <div class="container">

        <!-- Post -->
        <div class="row my-5 py-5">

            <div class="col-12">

                <!-- Card -->
                <div class="card card-body mb-5 px-0 py-0">

                    <div class="post-data mb-4 ml-4 mt-4">

                        <p class="font-small dark-grey-text mb-1">

                            <strong>Author:</strong> {{ post.author }}</p>

                        <p class="font-small grey-text mb-0">

                            <i class="far fa-clock-o"></i> {{ post.publish }}</p>

                        <a>

                            <span class="badge indigo">{{ post.category.name }}</span>

                        </a>

                    </div>

                    <!-- Title -->
                    <h1 class="font-weight-bold mt-3 text-center">

                        <strong>{{ post.title }}</strong>

                    </h1>

                    <hr class="red title-hr">

                    <img src="{{ post.image.url }}"
                         class="img-fluid z-depth-1 mx-4 rounded"
                         alt="sample image">

                    <!-- Grid row -->
                    <div class="row px-4">

                        <!-- Grid column -->
                        <div class="col-md-6 mt-4">

                            <h5 class="font-weight-bold dark-grey-text">

                                <i class="far fa-lg fa-newspaper mr-3 dark-grey-text"></i>

                                <strong>100</strong> Views</h5>

                        </div>
                        <!-- Grid column -->


                    </div>
                    <!-- Grid row -->

                    <!-- Grid row -->
                    <div class="row mx-md-5 px-md-4 px-5 mt-3">

                        <p class="dark-grey-text article">{{ post.body }}</p>

                    </div>
                    <!-- Grid row -->

                    <!-- Grid row -->
                    <hr>

                    <!-- Grid row -->
                    <div class="row mb-4">

                        <!-- Grid column -->
                        <div class="col-md-12 text-center">

                            <h4 class="text-center font-weight-bold dark-grey-text mt-3 mb-3">
                                <a href="{% url 'blog_app:post_share' post.id %}"><strong>Share this post </strong></a>
                            </h4>

                        </div>
                        <!-- Grid column -->

                    </div>

                    <!-- Grid row -->
                    <div class="container-fluid px-5" style="background-color: #d7dadf">

                        <h5 class="font-weight-bold mt-5">

                            <strong>YOU MIGHT ALSO LIKE</strong>

                        </h5>

                        <hr class="pink accent-3 title-hr">

                        <!-- Grid row -->
                        <div class="row mb-4">
                            {% for recommended_post in recommended_posts %}
                                <!-- Grid column -->
                                <div class="col-lg-4 my-3">

                                    <!-- Card -->
                                    <div class="card">

                                        <!-- Card image -->
                                        <div class="view overlay rgba-white-slight">

                                            <img src="{{ recommended_post.image.url }}"
                                                 class="card-img-top" alt="">

                                            <a>

                                                <div class="mask"></div>

                                            </a>

                                        </div>
                                        <!-- Card image -->
                                        <!-- Card content -->
                                        <div class="card-body">

                                            <!-- Title -->
                                            <h4 class="card-title">

                                                <strong>{{ recommended_post.title }}</strong>

                                            </h4>

                                            <hr>

                                            <!-- Text -->
                                            <p class="card-text mb-3">
                                                {{ recommended_post.body|truncatewords:3 }}
                                            </p>

                                            <p class="font-small font-weight-bold dark-grey-text mb-1">

                                                <i class="far fa-clock-o"></i> {{ recommended_post.publish }}/p>

                                            <p class="font-small grey-text mb-0">{{ recommended_post.author }}</p>

                                            <p class="text-right mb-0 font-small font-weight-bold">

                                                <a href="{{ recommended_post.get_absolute_url }}">read more

                                                    <i class="fas fa-angle-right"></i>

                                                </a>

                                            </p>

                                        </div>
                                        <!-- Card content -->

                                    </div>
                                    <!-- Card -->

                                </div>
                                <!-- Grid column -->
                            {% endfor %}

                        </div>
                        <!-- Grid row -->

                    </div>

                </div>

                <!-- Card -->

                <!-- Comments -->

                <section>

                    <!-- Main wrapper -->
                    <div class="comments-list text-center text-md-left">

                        <div class="text-center my-5">

                            <h3 class="font-weight-bold">Comments

                                <span class="badge indigo">{{ comments.count }}</span>

                            </h3>
                        </div>
                        {% for comment in comments %}
                            <!-- First row -->
                            <div class="row mb-5">

                                <!-- Image column -->
                                <div class="col-sm-2 col-12 mb-3">

                                    <img src="https://mdbootstrap.com/img/Photos/Avatars/img (8).jpg"
                                         class="avatar rounded-circle z-depth-1-half" alt="sample image">

                                </div>
                                <!-- Image column -->

                                <!-- Content column -->
                                <div class="col-sm-10 col-12">

                                    <a>

                                        <h5 class="user-name font-weight-bold">{{ comment.name }}</h5>

                                    </a>

                                    <div class="card-data">

                                        <ul class="list-unstyled">

                                            <li class="comment-date font-small">

                                                <i class="far fa-clock-o"></i> {{ comment.time }}
                                            </li>

                                        </ul>

                                    </div>

                                    <p class="dark-grey-text article">{{ comment.message }}</p>

                                </div>
                                <!-- Content column -->

                            </div>
                            <!-- First row -->
                        {% endfor %}


                    </div>
                    <!-- Main wrapper -->

                </section>
                <!-- Comments -->

                <!-- Section: Leave a reply (Not Logged In User) -->
                <section class="mb-4 mt-4">

                    <!-- Grid row -->
                    <div class="row">

                        <!-- Grid column -->
                        <div class="col-lg-12">

                            <!-- Leave a reply form -->
                            <div class="reply-form">

                                <h3 class="text-center h3 pt-5">Leave a reply </h3>

                                <form action="" method="post">
                                    <div class="md-form">
                                        <i class="fas fa-user prefix grey-text"></i>
                                        <label for="{{ form.name.id_for_label }}">Your name</label>
                                        {{ form.name|add_style:"form-control" }}
                                    </div>

                                    <div class="md-form">
                                        <i class="fas fa-envelope prefix grey-text"></i>
                                        <label for="{{ form.email.id_for_label }}">Your Email</label>
                                        {{ form.email|add_style:"form-control" }}
                                    </div>

                                    <div class="md-form">
                                        <i class="fas fa-pencil-alt prefix grey-text"></i>
                                        <label for="{{ form.message.id_for_label }}">Your Message</label>
                                        {{ form.message|add_style:"md-textarea form-control" }}

                                    </div>
                                    {% csrf_token %}
                                    <div class="text-center mt-4">
                                        <input type="submit" value="submit" class="btn btn-indigo btn-rounded">
                                    </div>
                                </form>
                            </div>
                            <!-- Leave a reply form -->

                        </div>
                        <!-- Grid column -->

                    </div>
                    <!-- Grid row -->

                </section>
                <!-- Section: Leave a reply (Not Logged In User) -->

            </div>
            <!-- Post -->

        </div>
        <!-- Magazine -->

    </div>

</main>
<!-- Main layout -->

<!-- SCRIPTS -->
<!-- JQuery -->
<script type="text/javascript" src="{% static "js/jquery-3.4.1.min.js" %}"></script>
<!-- Tooltips -->
<script type="text/javascript" src="{% static "js/popper.min.js" %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static "js/mdb.min.js" %}"></script>

</body>

</html>

blog/templates/blog/share.html
{% load static %}
{% load blog_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Material Design Bootstrap Template</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{% static "css/mdb.min.css" %}" rel="stylesheet">

</head>

<body class="postpage-v2">

<!-- Navigation -->
<header>

    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark stylish-color-dark">

        <!-- Navbar brand -->
        <a class="navbar-brand" href="#">My Personal Blog</a>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">

            <span class="navbar-toggler-icon"></span>

        </button>

    </nav>
    <!-- Navbar -->

</header>
<!-- Navigation -->

<!-- Main layout -->
<main>

    <div class="container">
        {% if send %}
            <p class="alert-info">post is successfully send via email.</p>
        {% else %}
            <!-- Post -->
            <div class="row my-5 py-5">

                <div class="col-12">

                    <!-- Section: Leave a reply (Not Logged In User) -->
                    <section class="mb-4 mt-4">

                        <!-- Grid row -->
                        <div class="row">

                            <!-- Grid column -->
                            <div class="col-lg-12">

                                <!-- Leave a reply form -->
                                <div class="reply-form">

                                    <h3 class="text-center h3 pt-5">Share Post </h3>

                                    <form action="" method="post">
                                        <div class="md-form">
                                            <i class="fas fa-user prefix grey-text"></i>
                                            <label for="{{ form.name.id_for_label }}">Your name</label>
                                            {{ form.name|add_style:"form-control" }}
                                        </div>

                                        <div class="md-form">
                                            <i class="fas fa-envelope prefix grey-text"></i>
                                            <label for="{{ form.email.id_for_label }}">Your Email</label>
                                            {{ form.email|add_style:"form-control" }}
                                        </div>
                                        <div class="md-form">
                                            <i class="fas fa-envelope prefix grey-text"></i>
                                            <label for="{{ form.contact_email.id_for_label }}">Your Contact
                                                Email</label>
                                            {{ form.contact_email|add_style:"form-control" }}
                                        </div>

                                        <div class="md-form">
                                            <i class="fas fa-pencil-alt prefix grey-text"></i>
                                            <label for="{{ form.message.id_for_label }}">Your Message</label>
                                            {{ form.message }}
                                        </div>
                                        {% csrf_token %}
                                        <div class="text-center mt-4">
                                            <input type="submit" value="submit" class="btn btn-indigo btn-rounded">
                                        </div>
                                    </form>
                                </div>
                                <!-- Leave a reply form -->

                            </div>
                            <!-- Grid column -->

                        </div>
                        <!-- Grid row -->

                    </section>
                    <!-- Section: Leave a reply (Not Logged In User) -->

                </div>
                <!-- Post -->

            </div>
            <!-- Magazine -->
        {% endif %}
    </div>


</main>
<!-- Main layout -->

<!-- SCRIPTS -->
<!-- JQuery -->
<script type="text/javascript" src="{% static "js/jquery-3.4.1.min.js" %}"></script>
<!-- Tooltips -->
<script type="text/javascript" src="{% static "js/popper.min.js" %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static "js/mdb.min.js" %}"></script>

</body>

</html>